### ISSUE TITLE
Plowlist problem with a mega folder

### ISSUE THREAD

**Issue by kidburglar** [mcrapet/plowshare-module-mega#1]
Hi,

I would try a plowlist from a mega folder with this command :
plowlist 'https://mega.co.nz/#F!68wTHLab!nx9UQbcMZTsFEMhJvFu_ZQ'

I have this error :
Retrieving list (mega): https://mega.co.nz/#F!68wTHLab!nx9UQbcMZTsFEMhJvFu_ZQ
parse_json failed (json): "n"
Failed inside mega_list(), line 896, mega.sh
Failed inside mega_list() [1]

If you will more information ask it.

**Comment by kidburglar** [comment]
It is strange, if I import the folders in my mega account I can use plowlist.

**Comment by mcrapet** [comment]
There is some garbage characters after JSON file attributes. It makes `parson_json` fail.
Hope I fixed things here:
https://github.com/mcrapet/plowshare/commit/7ca51ac9acc796bcd5a51ac51e718450273d3b33

Filenames will have weird names but I can't do much about it.
