### ISSUE TITLE
Define the tmp directory

### ISSUE THREAD

**Issue by kidburglar** [mcrapet/plowshare-module-mega#10]
Hello, I just had the problem that plowdown say me that I missed some space.

I suppose that my tmp was not big enough
It's possible to add an options to define another tmp directory ?

Cheers.

**Comment by mcrapet** [comment]
Hi,

Try:
`plowdown --temp-directory=/tmp2`

**Comment by kidburglar** [comment]
Hi, I not saw this option.
It work nicely, thanks.
