### ISSUE TITLE
Missing file installing the module

### ISSUE THREAD

**Issue by mriverodorta** [mcrapet/plowshare-module-mega#11]
Hello, when i try to install the modules and run `./autogen.sh` the script throws an error like this
`./autogen.sh: 3: ./autogen.sh: autoreconf: not found`. There are files missing.

**Comment by mcrapet** [comment]
Hi,
You need `automake` and `autoconf` (aka _autotools_) to create Makefile.
Please do read: [INSTALL](https://github.com/mcrapet/plowshare-module-mega/blob/master/INSTALL) file.

**Comment by mriverodorta** [comment]
Thanks,

Now i'm getting this error when i execute `$ ./configure --enable-local` 

`./configure: line 3619: syntax error near unexpected token OPENSSL,'
./configure: line 3619: PKG_CHECK_MODULES(OPENSSL, libcrypto)'`

i did install the ubuntu necessary packages with 
`apt-get install libssl-dev gcc autoconf automake git`

**Comment by mcrapet** [comment]
`apt-get install pkg-config` (missing in documentation, I'll fix it).
Then rerun `./autogen.sh` to regenerate configure scripts.

**Comment by mriverodorta** [comment]
thanks, this time work's like a charm.
