### ISSUE TITLE
upload: Not working 

### ISSUE THREAD

**Issue by SSoft7** [mcrapet/plowshare-module-mega#13]
The plugin is doing infinite upload...never stops.please check

**Comment by mcrapet** [comment]
Hi, 
Logs and detailed information would be appreciated.

Please do read:
https://github.com/mcrapet/plowshare-modules-legacy/blob/master/CONTRIBUTING.md

Regards,
Matthieu

**Comment by SSoft7** [comment]
Hi,

I was actually using it With Rutorrent Fileuploader, and It was not showing any appropriate progress , but some hint about progress. it looked like never stopping.

when i did this on Terminal ,the upload finished but Too long time For a 500MB file upload at a 1GBps Server.
Also Please note that The File upload was initially Fast ,but at later stage when Chunk size is like 400/500 It progress very slow,
I don't know why it is like that. i have read why its slow.

There is a Rapidleech Plugin http://pastebin.com/g5RKRNLr which Works very fast , may be you can take a look and see if there is something that can be improved about this on Bash plugin.

Thanks

There is

**Comment by mcrapet** [comment]
Hi,

Did you used `--multi=` switch ?

**Comment by mcrapet** [comment]
No news.. Closing.
