### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by rEnr3n** [mcrapet/plowshare-module-mega#14]
URL: https://mega.nz/#!pV8XhSAR!aGcDd856MIN7591c-t4k55kxT9bpwbZr5WXP-8_FU5Y
Account: anonymous
Plowshare v2.1.3
Log: [log.txt](https://github.com/mcrapet/plowshare-module-mega/files/460756/log.txt)

Download starts fine in browser without account. Error says meta-MAC mismatch. Putting --ignore-crc doesn't help.

**Comment by mcrapet** [comment]
Hi,

URL works fine for me. Maybe your download was corrupted.
I noticed also something, file is big and tmpfs (`/tmp`) is often not so big. I used `--temp-directory` with my home directory to fix it.

<pre>
$ plowdown --temp-directory ~ 'https://mega.nz/#!pV8XhSAR!aGcDd856MIN7591c-t4k55kxT9bpwbZr5WXP-8_FU5Y'
</pre>
