### ISSUE TITLE
invaid MAC

### ISSUE THREAD

**Issue by zodman** [mcrapet/plowshare-module-mega#15]
plowdown  'https://mega.nz/#!8Z9y2K6S!MuBVU-IRD4Cu6JMN3mGse3y-C12FXtD4f84e3AKeY4o' -v4

meta-MAC mismatch! 7FCE1EDC029E638A expected

what happend here ?

**Comment by mcrapet** [comment]
Hi,

Links works fine here. Your download is probably corrupted.
