### ISSUE TITLE
base64: invalid option -- d

### ISSUE THREAD

**Issue by webdevguy525** [mcrapet/plowshare-module-mega#16]
I am using Mac OS, I am getting this issue

base64: invalid option -- d
Usage:	base64 [-dhvD] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -D, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
cbc_dec: command not found

Do you have any solution?

thanks

**Comment by mcrapet** [comment]
Hi,

I think this is another difference between GNU coreutils and BSD.

Can you try this:
```diff
diff --git a/module/mega.sh b/module/mega.sh
index 688b9fa..bc42c7a 100644
--- a/module/mega.sh
+++ b/module/mega.sh
@@ -64,7 +64,7 @@ base64_to_hex() {
            IN="${IN}="
            ;;
     esac
-    base64 -d < <(echo -n "${IN//-/+}") | hexdump -v -e '1/1 "%02X"'
+    base64 --decode < <(echo -n "${IN//-/+}") | hexdump -v -e '1/1 "%02X"'
 }
 
 # Ascii to hexstring + padding (add 1, 2 or 3 null bytes)
```
