### ISSUE TITLE
error when saving file

### ISSUE THREAD

**Issue by minipretzel** [mcrapet/plowshare-module-mega#2]
Seems to error out saving the following file:

https://mega.co.nz/#!ctZlCSRR!c8B8FkGGxD_YpHtj56KPk-JVNsof83lf_o5JYcX0ONA

error: can't open file, abort
error: can't open file, abort
error: can't open file, abort
error: can't open file, abort
error: can't open file, abort
error: can't open file, abort
error: can't open file, abort
error: can't open file, abort
meta-MAC mismatch! FE8E4961C5F438D0 expected
Failed inside mega_download() [1]

Can successfully download this using other programs.

**Comment by mcrapet** [comment]
Hi,
Do you still have troubles ?
