### ISSUE TITLE
MEGA is changing all new links from mega.co.nz to mega.nz.

### ISSUE THREAD

**Issue by j4gg3red** [mcrapet/plowshare-module-mega#4]
Adding '.co' the the new urls still works for plowdown.
Failing to do so returns the module not found for mega.nz exit code.

**Comment by zodman** [comment]
change a small on 
MODULE_MEGA_REGEXP_URL

**Comment by Al-eXs** [comment]
I just change that on my install.

Change the default to:

```
MODULE_MEGA_REGEXP_URL='https\?://\(www\.\)\?mega\.\(co\.\)\?nz/'
```

**Comment by zodman** [comment]
send a pull request!
