### ISSUE TITLE
mega plowdown faild

### ISSUE THREAD

**Issue by zodman** [mcrapet/plowshare-module-mega#9]
root@neko:~/downloads# plowdown 'https://mega.nz/#!lx4XBSjT!BijEAFSAgoyleNsTPdVX2IGG9DERnpFWMDOv8_7Nl2E'
Starting download (mega): https://mega.nz/#!lx4XBSjT!BijEAFSAgoyleNsTPdVX2IGG9DERnpFWMDOv8_7Nl2E
parse_json failed (json): "n"
Failed inside mega_download(), line 606, mega.sh
Failed inside mega_download() [1]

**Comment by mcrapet** [comment]
Hi,
Do you still have troubles?
